//! Uninstall plan: the structural mirror of `install::plan::InstallPlan`,
//! generated by translating each `PlanAction` into the matching
//! `Remove*` step. Building this plan is intentionally derived from the
//! install planner — uninstall **must** walk the same link-map shape
//! the installer wrote, otherwise overlay-added entries or recursive
//! expansions get orphaned in the runtime home.

use crate::install::link_map::CommentStyle;
use crate::install::plan::{InstallPlan, PlanAction};
use std::path::PathBuf;

/// One step the uninstall executor will run.
#[derive(Debug, Clone)]
pub enum UninstallAction {
    /// Remove the symlink at `dest` if it points at `expected_source`.
    /// When the symlink target differs (operator manually replaced) or
    /// `dest` is a regular file (foreign content), the executor leaves
    /// the file in place and emits a `Skipped*` change.
    RemoveSymlink {
        entry_id: String,
        /// Absolute install source the symlink was created against.
        /// Compared byte-for-byte against `read_link(dest)`.
        expected_source: PathBuf,
        dest: PathBuf,
    },
    /// Remove the managed block at `config_file`. No-op when no markers
    /// are present; errors only when markers are unbalanced.
    RemoveManagedBlock {
        entry_id: String,
        config_file: PathBuf,
        surface: String,
        comment_style: CommentStyle,
    },
}

/// Resolved uninstall plan. Each entry in `actions` is ready to run;
/// the executor mutates the filesystem only in `Mode::Apply`.
#[derive(Debug, Clone)]
pub struct UninstallPlan {
    pub product: String,
    pub home: PathBuf,
    pub actions: Vec<UninstallAction>,
}

impl UninstallPlan {
    /// Build an uninstall plan by translating each `PlanAction` from the
    /// install planner. Action order matches the install planner's
    /// declaration order — uninstall does not need parent-directory
    /// pruning, so reverse-order traversal is not required.
    pub fn from_install(install: &InstallPlan) -> Self {
        let mut actions = Vec::with_capacity(install.actions.len());
        for action in &install.actions {
            match action {
                PlanAction::Symlink {
                    entry_id,
                    source,
                    dest,
                    requires_backup: _,
                } => {
                    actions.push(UninstallAction::RemoveSymlink {
                        entry_id: entry_id.clone(),
                        expected_source: source.clone(),
                        dest: dest.clone(),
                    });
                }
                PlanAction::ManagedBlock {
                    entry_id,
                    config_file,
                    surface,
                    comment_style,
                    body: _,
                } => {
                    actions.push(UninstallAction::RemoveManagedBlock {
                        entry_id: entry_id.clone(),
                        config_file: config_file.clone(),
                        surface: surface.clone(),
                        comment_style: *comment_style,
                    });
                }
            }
        }
        Self {
            product: install.product.clone(),
            home: install.home.clone(),
            actions,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::install::link_map::{EntryKind, LinkEntry, LinkMap};
    use std::path::Path;
    use tempfile::TempDir;

    fn write_source_tree(tmp: &Path) {
        std::fs::create_dir_all(tmp.join("build/claude/plugins/reporting/skills")).unwrap();
        std::fs::write(
            tmp.join("build/claude/plugins/reporting/skills/SKILL.md"),
            "x",
        )
        .unwrap();
    }

    #[test]
    fn translation_preserves_action_order_and_kinds() {
        let tmp = TempDir::new().unwrap();
        write_source_tree(tmp.path());
        let lm = LinkMap {
            schema_version: 1,
            entries: vec![
                LinkEntry {
                    id: "reporting.skills".to_string(),
                    kind: EntryKind::SymlinkedFile,
                    source: Some("build/claude/plugins/reporting/skills".to_string()),
                    destination: "plugins/reporting/skills".to_string(),
                    recursive: true,
                    surface: None,
                    comment_style: None,
                    body_template: None,
                },
                LinkEntry {
                    id: "claude.config".to_string(),
                    kind: EntryKind::ManagedBlock,
                    source: None,
                    destination: "settings.json".to_string(),
                    recursive: false,
                    surface: Some("install".to_string()),
                    comment_style: Some(CommentStyle::DoubleSlash),
                    body_template: Some("\"x\": 1".to_string()),
                },
            ],
        };
        let install = InstallPlan::build(
            "claude",
            tmp.path(),
            Path::new("/sandbox/home"),
            Path::new("/sandbox/state"),
            &lm,
        )
        .unwrap();
        let plan = UninstallPlan::from_install(&install);
        assert_eq!(plan.product, "claude");
        assert_eq!(plan.actions.len(), install.actions.len());
        // First action is a symlink removal (the recursive entry's first
        // expansion), last is the managed-block removal.
        assert!(matches!(
            plan.actions.first().unwrap(),
            UninstallAction::RemoveSymlink { .. }
        ));
        assert!(matches!(
            plan.actions.last().unwrap(),
            UninstallAction::RemoveManagedBlock { .. }
        ));
    }
}
