[package]
name = "nils-test-first-evidence"
version = "0.10.2"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-test-first-evidence in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[lib]
name = "test_first_evidence"
path = "src/lib.rs"

[[bin]]
name = "test-first-evidence"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
nils-common = { version = "0.10.2", path = "../nils-common", package = "nils-common" }
regex = "1"
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
nils-test-support = { version = "0.10.2", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
